root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "docker"]
include_dir = []
exclude_file = []
delay = 1000 # ms
kill_delay = "0.5s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[log]
time = true
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true